name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Use MySql"
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql root password: rootroot

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --password=rootroot --silent; do
            sleep 1
          done
      - name: Generate Prisma Client
        run: npx prisma generate --schema ./src/hermit/prisma/schema.prisma

      - name: Configure Mysql
        run: |
          mysql -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'rootroot';" -h 127.0.0.1 -u root -prootroot
          mysql -e "flush privileges;" -h 127.0.0.1 -u root -prootroot

      - name: Run tests
        run: npm test
